{{- $fullName := include "directus.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "directus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "directus.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:

      initContainers:
        - command:
            - /bin/sh
          args:
            - '-c'
            - mkdir -p /tmp_mount/{{ $fullName }}
            # - mkdir -p /tmp_mount/{{ $fullName }}/database && mkdir -p /tmp_mount/{{ $fullName }}/uploads && mkdir -p /tmp_mount/{{ $fullName }}/extensions
          image: busybox:1.35.0
          imagePullPolicy: IfNotPresent
          name: prepare-nfs-dirs
          {{- if and .Values.storage.nfs.hostname .Values.storage.nfs.path }}
          volumeMounts:
            - mountPath: /tmp_mount
              name: vol-{{ $fullName }}-nfs
          {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: KEY
              value: {{ .Values.envVars.directus.key }}
            - name: SECRET
              value: {{ .Values.envVars.directus.secret }}

            - name: ADMIN_EMAIL
              value: {{ .Values.envVars.directus.adminEmail }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.envVars.directus.adminPassword }}

            - name: DB_CLIENT
              value: {{ .Values.envVars.directus.dbClient }}
            - name: DB_HOST
              value: {{ .Values.envVars.directus.dbHost }}
            - name: DB_PORT
              value: '{{ .Values.envVars.directus.dbPort }}'
            - name: DB_USER
              value: {{ .Values.envVars.directus.dbUser }}
            - name: DB_PASSWORD
              value: {{ .Values.envVars.directus.dbPass }}
            - name: DB_DATABASE
              value: {{ .Values.envVars.directus.dbDatabase }}

            - name: EMAIL_TRANSPORT
              value: {{ .Values.envVars.directus.emailTransport }}
            - name: EMAIL_SMTP_HOST
              value: {{ .Values.envVars.directus.emailSmtpHost }}
            - name: EMAIL_SMTP_PORT
              value: '{{ .Values.envVars.directus.emailSmtpPort }}'
            - name: EMAIL_SMTP_IGNORE_TLS
              value: '{{ .Values.envVars.directus.emailSmtpIgnoreTls }}'

            {{- if .Values.ingress.enabled }}
            - name: PUBLIC_URL
              value: 'http://{{ .Values.ingress.hostUrl }}'
              # value: {{ .Values.envVars.directus.publicUrl }}
            {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if and .Values.storage.nfs.hostname .Values.storage.nfs.path }}
          volumeMounts:
            - mountPath: /directus/database
              name: vol-{{ $fullName }}-nfs
              subPath: {{ $fullName }}/database
            - mountPath: /directus/uploads
              name: vol-{{ $fullName }}-nfs
              subPath: {{ $fullName }}/uploads
            - mountPath: /directus/extensions
              name: vol-{{ $fullName }}-nfs
              subPath: {{ $fullName }}/extensions
          {{- end }}

      {{- if and .Values.storage.nfs.hostname .Values.storage.nfs.path }}
      volumes:
        - name: vol-{{ $fullName }}-nfs
          nfs:
            server: {{ .Values.storage.nfs.hostname }}
            path: {{ .Values.storage.nfs.path }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
