{{- if .Values.externalApp.skipCertVerify -}}
{{- $fullName := include "external-app-lb.fullname" . -}}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ $fullName }}-tst # tst: Traefik Servers Transport
spec:
  insecureSkipVerify: true # Skip SSL verification
{{- end }}
