# Default values for pgadmin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pgadmin:
    repository: dpage/pgadmin4
    pullPolicy: IfNotPresent
    tag: "8.5"

envVars:
  pgadmin:
    adminEmail: ""
    adminPass: ""
    maxLoginAttempts: 3

    configureMail: false
    mailServer: ""
    mailPort: ""
    mailUseSSL: ""
    mailUseTLS: ""

service:
  pgadmin:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: ""
  tlsEnabled: true
  forceHttps: true
  issuer: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostUrl: "test-pgadmin.test"
  hostPath: /
  hostPathType: Prefix 

storage:
  nfs:
    hostname: "nfs-server.test"
    path: "/volume/nfs/path"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
