# Default values for rancher-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: rancher-demo
replicaCount: 1

image:
  repository: bashofmann/rancher-demo
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

podAnnotations: {}
podLabels:
  app: rancher-demo

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}
