# Default values for n8n.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  n8n:
    repository: n8nio/n8n
    pullPolicy: IfNotPresent
    tag: "1.36.1"

envVars:
  n8n:
    # DB VARIABLES
    dbType: "postgresdb"
    dbHost: ""
    dbPort: "5432"
    dbName: "n8n"
    dbUser: "n8n-user"
    dbPass: ""

    # EMAIL VARIABLES
    configureMail: false
    emailMode: "smtp"

    # SMTP VARIABLES
    smtpHost: ""
    smtpPort: "25"
    smtpSender: ""
    smtpSsl: "false"

    # OTHERS
    logLevel: "info"

service:
  n8n:
    type: ClusterIP
    port: 80

