{{- $fullName := include "postgresql.fullname" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-cip
  labels:
    app: postgresql
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: db
      port: {{ .Values.service.postgresql.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
