# Default values for xo-cluster-cert.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

certmanager:
  issuerKind: "" # Issuer or ClusterIssuer.
  acme:
    email: "" 
    privateKeySecretRef: ""
