{{- if eq .Values.certmanager.issuerType "letsencrypt" -}}
{{- if .Values.certmanager.deployProdIssuer -}}
{{- $fullName := include "xo-cluster-cert.fullname" . -}}

apiVersion: cert-manager.io/v1
kind: {{ .Values.certmanager.issuerKind }}
metadata:
  name: {{ .Release.Name }}-prod

  {{- if eq .Values.certmanager.issuerKind "Issuer" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}

spec:
  acme:
    # The ACME server URL
    server: {{ .Values.certmanager.letsencrypt.serverProductionUrl }} 
    # Email address used for ACME registration
    email: {{ .Values.certmanager.acme.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      {{- if .Values.certmanager.acme.privateKeySecretRef }}
      name: {{ .Values.certmanager.acme.privateKeySecretRef }}-prod
      {{- else }}
      name: {{ $fullName }}-lets-secret-prod
      {{- end }}

    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          # TODO: Add multiple ingress classes.
          ingressClassName: traefik
{{- end }}
{{- end }}
