{{- $fullName := include "external-app-lb.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-in
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "external-app-lb.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.ingress.issuer .Values.ingress.forceHttps }}
  annotations:
  {{- if .Values.ingress.issuer }}
    cert-manager.io/issuer: {{ .Values.ingress.issuer }}
  {{- end }}
  {{- if .Values.ingress.forceHttps }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace }}-{{ $fullName }}-tm-tohttps@kubernetescrd
  {{- end }}
  {{- if .Values.ingress.annotations }}
  {{- range $key, $value := .Values.ingress.annotations }}
  {{- if $value }}
    {{ $key }}: {{ $value }} 
  {{- end }}
  {{- end }}

  {{- end }}
  {{- end }}
spec:
  {{- if and .Values.ingress.tlsEnabled .Values.ingress.issuer }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if and .Values.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
