{{- $fullName := include "external-app-lb.fullname" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  {{- if or .Values.externalApp.isHttps .Values.externalApp.skipCertVerify }}
  annotations:
  {{- if .Values.externalApp.isHttps }}
    traefik.ingress.kubernetes.io/service.serversscheme: https
  {{- end }}
  {{- if .Values.externalApp.skipCertVerify }}
    traefik.ingress.kubernetes.io/service.serverstransport: {{ .Values.namespace }}-{{ $fullName }}-tst@kubernetescrd
  {{- end }}
  {{- end }}
  labels:
    {{- include "external-app-lb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
