{{- if .Values.ingress.forceHttps -}}
{{- $fullName := include "external-app-lb.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-tm-tohttps
  namespace: {{ .Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
